# Docker compose para odoo con persistencia en
# datos en postgres
# addons y datos en odoo

services:
  odoo:
    image: odoo:17.0
    container_name: odoo
    restart: unless-stopped
    user: root
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "18070:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./volumenes/odoo-data/filestore:/var/lib/odoo/filestore
      - ./volumenes/odoo-data/sessions:/var/lib/odoo/sessions
      - ./addons:/mnt/extra-addons
  #   - /home/alumno/Documentos/addons:/mnt/extra-addons

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

    volumes:
      - ./volumenes/odoo-db:/var/lib/postgresql/data

volumes:
  odoo-data:
  odoo-db:
  addons:
