version: '3.3'

services:

  odoo:
    image: odoo:17.0
    container_name: odoo
    restart: unless-stopped
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "18070:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - /home/alumno/Documentos/modulos:/mnt/extra-addons

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      
    volumes:
      - odoo-db:/var/lib/postgresql/data
      
volumes:
  odoo-data:
  odoo-db:
